name: Docker Build and Push to ECR

on:
  workflow_call:
    secrets:
      docker_secrets:
        description: "Comma-delimited list of Github secrets to pass to docker build workflow"
        required: false
    inputs:
      environment:
        description: "Environment to run the build in"
        type: string
      aws_account_id:
        description: "AWS Account ID"
        type: string
      aws_region:
        description: "AWS Region"
        type: string
      aws_role_name:
        description: "AWS Role Name"
        type: string
      aws_oidc_role_arn:
        description: "AWS OIDC IAM role to assume"
        type: string
      image_name:
        description: "Name of the Docker image to build"
        type: string
      image_tag:
        description: "Tag of the Docker image to build as string (csv allowed) or as JSON encoded list"
        type: string
      image_labels:
        description: "Labels to apply to the Docker image as JSON encoded list"
        type: string
      docker_context:
        description: "Path to the build context"
        type: string
      dockerfile_path:
        description: "Path to the Dockerfile. If not defined, will default to {docker_context}/Dockerfile"
        type: string
      docker_push:
        description: "Push Image to ECR"
        type: boolean
        default: true
      docker_target:
        description: "Build target"
        type: string
      docker_build_args:
        description: "Build arguments to pass to the docker build as json encoded list"
        type: string
      docker_platforms:
        description: "Platforms to build for. If empty docker will build for the current platform"
        type: string
      artifact_name:
        description: "Artifact name to be downloaded before building"
        type: string
      artifact_path:
        description: "Artifact target path"
        type: string
      runner_labels:
        description: "Runner that the main job should run on as JSON encoded list."
        type: string
        default: " ['ubuntu-latest'] "


jobs:
  prereq:
    runs-on: ubuntu-latest
    steps:
      - name: Provision step # at least one step is required in a job
        run: |
          echo "Provisioning ${{ inputs.runner_labels }}"
    outputs:
      runner_labels: ${{ inputs.runner_labels }}
  build:
    needs: prereq
    runs-on: ${{ fromJSON(needs.prereq.outputs.runner_labels) }}
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Download artifacts to pass to docker build
        if: ${{ inputs.artifact_name || inputs.artifact_path }} # avoid downloading artifacts if not needed
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4
        env:
          ARTIFACT_NAME: ${{ inputs.artifact_name || vars.artifact_name }}
          ARTIFACT_PATH: ${{ inputs.artifact_path || vars.artifact_path }}
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_PATH }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4
        env:
          ROLE_TO_ASSUME: ${{ inputs.aws_oidc_role_arn || vars.aws_oidc_role_arn || format('arn:aws:iam::{0}:role/{1}', inputs.aws_account_id, inputs.aws_role_name) }}
          AWS_REGION: ${{ inputs.aws_region || vars.aws_region || 'eu-central-1' }}
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2

      - name: Set docker image tags from input if set
        if: ${{ inputs.image_tag }}
        run: |
          INPUT=${{ inputs.image_tag }}
          echo $INPUT | jq -r '. | @csv'  > /dev/null 2>&1
           if [ $? -eq 0 ]; then
            echo "Input is valid JSON"
            tags_as_csv=$(echo $INPUT | jq -r '. | @csv')
            echo "IMAGE_TAG=$tags_as_csv" >> $GITHUB_ENV
          else
            echo "Input is a string. Passing it as is."
            echo "IMAGE_TAG=$INPUT" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Set docker image tags from sha if not set
        if: ${{ !inputs.image_tag }}
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ inputs.image_name || vars.image_name || github.event.repository.name }}
        run: |
          echo "IMAGE_TAG=${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ github.sha }}" >> $GITHUB_ENV
        shell: bash

      - name: Set docker image labels from input if set
        if: ${{ inputs.image_labels }}
        id: set-docker-labels
        run: |
          INPUT=${{ inputs.image_labels }}
          echo $INPUT | jq -r '.'  > /dev/null 2>&1
           if [ $? -eq 0 ]; then
            echo "Input is valid JSON"
            labels_as_list=$(echo $INPUT | jq -c '.' | jq -c 'to_entries | map("\(.key)=\(.value)") | .[]')
            echo "IMAGE_LABELS=$labels_as_list" >> "$GITHUB_OUTPUT"
          else
            echo "Input is a string. Passing it as is."
            echo "IMAGE_LABELS=$INPUT" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Set docker build args from input if set
        if: ${{ inputs.docker_build_args }}
        run: |
          INPUT=${{ inputs.docker_build_args }}
          echo $INPUT | jq -r '.'  > /dev/null 2>&1
           if [ $? -eq 0 ]; then
            echo "Input build args is valid JSON"
            build_args_as_list=$(echo $INPUT  | jq -r '.' | jq -r 'to_entries | map("\(.value)")| @csv')
            # echo "DOCKER_BUILD_ARGS=$build_args_as_list" >> $GITHUB_ENV
            # args_as_list='${{ fromJSON(inputs.docker_build_args) }}'
            echo "DOCKER_BUILD_ARGS=$args_as_list'" >> "$GITHUB_OUTPUT" 
          else
            echo "Input is a string. Passing it as is."
            echo "DOCKER_BUILD_ARGS=$INPUT" >> $GITHUB_OUTPUT
          fi

      - name: Build and export
        uses: docker/build-push-action@31159d49c0d4756269a0940a750801a1ea5d7003 # v6
        env:
          DOCKER_CTX: ${{ inputs.docker_context || vars.docker_context || '.' }}
          DOCKERFILE_PATH: ${{ inputs.dockerfile_path || vars.dockerfile_path }} # upstream defaults to {DOCKER_CTX}/Dockerfile
          DOCKER_TARGET: ${{ inputs.docker_target || vars.docker_target }}
        with:
          context: ${{ env.DOCKER_CTX }}
          file: ${{ env.DOCKERFILE_PATH }}
          secrets: ${{ secrets.docker_secrets }}
          platforms: ${{ inputs.docker_platforms }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: ${{ inputs.docker_push }}
          target: ${{ env.DOCKER_TARGET }}
          tags: ${{ env.IMAGE_TAG }}
          labels: ${{ steps.set-docker-labels.outputs.IMAGE_LABELS }}
          build-args: ${{ steps.set-docker-build-args.outputs.DOCKER_BUILD_ARGS }}