name: Docker

on:
  workflow_call:
    inputs:
      aws_account_id:
        description: 'AWS Account ID'
        type: string
        required: true
      aws_region:
        description: 'AWS Region'
        type: string
        required: true
      aws_role_name:
        description: 'AWS Role Name'
        type: string
        required: true
      image_name:
        description: 'Name of the Docker image to build'
        type: string
        required: false
        default: ${{ github.event.repository.name }}
      image_tag:
        description: 'Tag of the Docker image to build'
        type: string
        required: false
        default: ${{ github.sha }}
      docker_context:
        description: 'Path to the build context'
        type: string
        required: false
        default: .
      artifact_retention_days:
        description: 'Number of days to retain the artifact'
        type: number
        required: false
        default: 5

permissions:
  id-token: write
  contents: read

jobs:
  push:
    name: Push to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.image_name }}-${{ github.sha }}
          path: /tmp

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ inputs.aws_account_id }}:role/${{ inputs.aws_role_name }}
          aws-region: ${{ inputs.aws_region }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ inputs.image_name }}
          SOURCE_TAG: ${{ github.sha }}
          IMAGE_TAG: ${{ inputs.image_tag }}
          BRANCH: ${{ github.head_ref }}
        run: |
          docker load -i /tmp/$REPOSITORY.tar
          docker tag $REPOSITORY:$SOURCE_TAG $REGISTRY/$REPOSITORY:$SOURCE_TAG
          docker tag $REPOSITORY:$SOURCE_TAG $REGISTRY/$REPOSITORY:$IMAGE_TAG

          if [ $BRANCH == 'main' ] or [ $BRANCH == 'master' ]; then
            docker tag $REPOSITORY:$SOURCE_TAG $REGISTRY/$REPOSITORY:latest
          fi

          docker image push --all-tags $REPOSITORY:$SOURCE_TAG
