name: Docker Build

on:
  workflow_call:
    inputs:
      environment:
        description: "Environment to deploy"
        type: string
      image_name:
        description: "Name of the Docker image to build"
        type: string
      docker_context:
        description: "Path to the build context"
        type: string
      artifact_name:
        description: "Name of the artifact to upload. If not set, it will be derived from the image name"
        type: string
      artifact_retention_days:
        description: "Number of days to retain the artifact"
        type: number
      docker_target:
        description: "Build target"
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    env:
      IMAGE_TAG: ${{ github.event.pull_request.head.sha || github.sha }}
      IMAGE_NAME: ${{ inputs.image_name || vars.image_name || github.event.repository.name }}
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3

      - name: Build and export
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        env:
          DOCKER_CTX: ${{ inputs.docker_context || vars.docker_context || '.'}}
          DOCKER_TARGET: ${{ inputs.docker_target || vars.docker_target }}
        with:
          context: ${{ env.DOCKER_CTX }}
          # platforms: linux/amd64,linux/arm64 # TODO add support for multi-arch builds
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          outputs: type=docker,dest=/tmp/${{ env.IMAGE_NAME }}.tar
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: ${{ env.DOCKER_TARGET }}

      - name: Upload artifact
        env:
          ARTIFACT_RETENTION_DAYS: ${{ inputs.artifact_retention_days || vars.artifact_retention_days || 5 }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: ${{ inputs.artifact_name || env.IMAGE_NAME }}-${{ env.IMAGE_TAG }}
          path: /tmp/${{ inputs.artifact_name || env.IMAGE_NAME }}.tar
          retention-days: ${{ env.ARTIFACT_RETENTION_DAYS }}
