name: Helm Diff Preview

on:
  workflow_call:
    inputs:
      helm_chart_path:
        description: 'Path to the Helm chart directory'
        type: string
        default: 'deploy/app'
      environments_path:
        description: 'Path to the directory containing environment-specific values'
        type: string
        default: 'deploy/app/envs'
      output_path:
        description: 'Path to the output directory for diffs'
        type: string
        default: 'output'
      base_branch:
        description: 'Base branch for comparison'
        type: string
        default: ${{ github.event.pull_request.base.ref }}
      helm_release_name:
        description: 'Name to use for the Helm release when templating'
        type: string
        default: 'app'
      helm_repo_url:
        description: 'URL of the Helm repository to add'
        type: string
        default: 'https://dnd-it.github.io/helm-charts'
      helm_repo_name:
        description: 'Name to give to the Helm repository'
        type: string
        default: 'dnd-it'
      debug:
        description: 'Enable debug output'
        type: string
        default: 'false'

env:
  HELM_CHART_PATH: ${{ inputs.helm_chart_path }}
  ENVIRONMENTS_PATH: ${{ inputs.environments_path }}
  OUTPUT_PATH: ${{ inputs.output_path }}
  HELM_RELEASE_NAME: ${{ inputs.helm_release_name }}

jobs:
  diff:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    outputs:
      chart_changed: ${{ steps.changed-files.outputs.chart_values_any_changed }}
      env_values_changed: ${{ steps.changed-files.outputs.env_values_any_changed }}
      env_values_files: ${{ steps.filter-envs.outputs.env_values_files }}
      env_list: ${{ steps.filter-envs.outputs.env_list }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v47
        with:
          files_yaml: |
            chart_values:
              - ${{ env.HELM_CHART_PATH }}/values.yaml
              - ${{ env.HELM_CHART_PATH }}/Chart.yaml
            env_values:
              - ${{ env.ENVIRONMENTS_PATH }}/**/*.yaml

      - name: Filter changed environments
        id: filter-envs
        env:
          ENV_VALUES_FILES: ${{ steps.changed-files.outputs.env_values_all_changed_files }}
        run: |
          # Get list of all changed env value files
          echo "env_values_files=$ENV_VALUES_FILES" >> $GITHUB_OUTPUT

          # Extract environment names from paths
          ENV_LIST=""
          if [ -n "$ENV_VALUES_FILES" ]; then
            ENV_LIST=$(echo "$ENV_VALUES_FILES" | xargs -n1 dirname | xargs -n1 basename | sort -u | tr '\n' ' ')
          fi

          # If chart values changed, we need to check all environments
          if [ "${{ steps.changed-files.outputs.chart_values_any_changed }}" == "true" ]; then
            # Get all environments by listing directories
            ALL_ENVS=$(find ${{ env.ENVIRONMENTS_PATH }} -maxdepth 1 -type d | xargs -n1 basename | grep -v "^${ENVIRONMENTS_PATH##*/}$" | tr '\n' ' ')
            if [ -n "$ALL_ENVS" ]; then
              ENV_LIST="$ALL_ENVS"
            fi
          fi

          echo "env_list=$ENV_LIST" >> $GITHUB_OUTPUT
          echo "Environments to diff: $ENV_LIST"

      - name: Show debug info
        if: inputs.debug == 'true'
        run: |
          echo "Chart values changed: ${{ steps.changed-files.outputs.chart_values_any_changed }}"
          echo "Environment values changed: ${{ steps.changed-files.outputs.env_values_any_changed }}"
          echo "Changed environment files: ${{ steps.changed-files.outputs.env_values_all_changed_files }}"
          echo "Environments to check: ${{ steps.filter-envs.outputs.env_list }}"

      - name: Checkout target branch
        uses: actions/checkout@v5
        if: steps.changed-files.outputs.chart_values_any_changed == 'true' || steps.changed-files.outputs.env_values_any_changed == 'true'
        with:
          ref: ${{ inputs.base_branch }}
          path: target-branch

      - name: Set up Helm
        if: steps.changed-files.outputs.chart_values_any_changed == 'true' || steps.changed-files.outputs.env_values_any_changed == 'true'
        run: |
          helm repo add ${{ inputs.helm_repo_name }} ${{ inputs.helm_repo_url }}
          helm dependency build ${{ env.HELM_CHART_PATH}}
          helm dependency build target-branch/${{ env.HELM_CHART_PATH}}

      - name: Process environments
        if: steps.changed-files.outputs.chart_values_any_changed == 'true' || steps.changed-files.outputs.env_values_any_changed == 'true'
        id: process-envs
        run: |
          mkdir -p ${{ env.OUTPUT_PATH }}
          echo "## Helm Deployment Changes" > ${{ env.OUTPUT_PATH }}/all_diffs.md
          echo "" >> ${{ env.OUTPUT_PATH }}/all_diffs.md

          HAS_CHANGES=false

          for ENV in ${{ steps.filter-envs.outputs.env_list }}; do
            echo "Processing environment: $ENV"

            # Check if environment directory exists in both branches
            if [ ! -d "${{ env.ENVIRONMENTS_PATH }}/$ENV" ] || [ ! -d "target-branch/${{ env.ENVIRONMENTS_PATH }}/$ENV" ]; then
              echo "Warning: Environment directory $ENV does not exist in one or both branches, skipping"
              continue
            fi

            # Generate rendered output for PR branch with environment values

            helm template ${{ env.HELM_RELEASE_NAME}} ${{ env.HELM_CHART_PATH}} \
              -f ${{ env.ENVIRONMENTS_PATH }}/$ENV/values.yaml \
              > rendered-$ENV.yaml

            # Generate rendered output for target branch with environment values
            helm template ${{ env.HELM_RELEASE_NAME}} target-branch/${{ env.HELM_CHART_PATH}} \
              -f target-branch/${{ env.ENVIRONMENTS_PATH }}/$ENV/values.yaml \
              > target-branch/rendered-$ENV.yaml

            # Generate diff for this environment
            diff -u target-branch/rendered-$ENV.yaml rendered-$ENV.yaml > ${{ env.OUTPUT_PATH }}/diff-$ENV.txt || true

            # Check if diff exists and add to summary
            if [ -s ${{ env.OUTPUT_PATH }}/diff-$ENV.txt ]; then
              HAS_CHANGES=true
              echo "### Environment: $ENV" >> ${{ env.OUTPUT_PATH }}/all_diffs.md
              echo "" >> ${{ env.OUTPUT_PATH }}/all_diffs.md

              echo "<details><summary>Changes detected for $ENV environment:</summary>" >> ${{ env.OUTPUT_PATH }}/all_diffs.md
              echo "" >> ${{ env.OUTPUT_PATH }}/all_diffs.md
              echo '```diff' >> ${{ env.OUTPUT_PATH }}/all_diffs.md
              cat ${{ env.OUTPUT_PATH }}/diff-$ENV.txt >> ${{ env.OUTPUT_PATH }}/all_diffs.md
              echo '```' >> ${{ env.OUTPUT_PATH }}/all_diffs.md
              echo "</details>" >> ${{ env.OUTPUT_PATH }}/all_diffs.md
              echo "" >> ${{ env.OUTPUT_PATH }}/all_diffs.md
            fi
          done

          echo "has_changes=$HAS_CHANGES" >> $GITHUB_OUTPUT

      - name: Post diff as comment on PR
        if: steps.process-envs.outputs.has_changes == 'true'
        run: |
          gh pr comment ${{ github.event.number }} --repo ${{ github.repository }} --body-file ${{ env.OUTPUT_PATH }}/all_diffs.md --edit-last || \
          gh pr comment ${{ github.event.number }} --repo ${{ github.repository }} --body-file ${{ env.OUTPUT_PATH }}/all_diffs.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
